[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_program = "SBeGFPgyp2C9Jf7gd2BsdochFXQS9KD3KWn3BkQcAoF"

[programs.devnet]
solana_program = "SBeGFPgyp2C9Jf7gd2BsdochFXQS9KD3KWn3BkQcAoF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
